### ISSUE TITLE
Undefined variable 'ISO12233Charthv'

### ISSUE THREAD

**Issue by danieleceUL** [OlivervZ11/NS-SFR#1]
Hi all:

I've been using this repository for SFR measurements on my dataset and for the second script 'Pt2_ESFR_Estimation.m' I am getting an undefined error with test chart data.
I tried using 'addpath('Part 2/')' to the top of the file but this didn't work.
Has anyone come across this issue before?

**Comment by OlivervZ11** [comment]
Hi Dan, 
Thank you for your inquiry. Sorry for my delayed response, you caught me a couple of weeks where I was moving house. 
I believe I know what is happening, the test chart data must be in a certain format for 'Pt2_ESFR_Estimation.m' to read. Alternatively, you should press 'No' to the loading of the chart data.  

I suggest using my updated code, available as either MATLAB code or user interface (GUI). It has been optimized for e-SFR estimation. I have also included a MATLAB tool to select test chart edges and output the correct file format for test chart comparisons. It is available at: https://github.com/OlivervZ11/NSSFR-GUI

Please get in touch with any other problems. 
Kind Regards,
Oliver van Zwanenberg

**Comment by danieleceUL** [comment]
Hi Oliver:-

This is brilliant! Thank you so much for your reply!
I can see the README file has completely changed since I last looked at it this week. I would like to congratulate you for research on this topic. I am very impressed by it. I am certain that your work and research will be crucial for my experiments. I am a first year PhD student at University of Limerick (feel free to connect with me on LinkedIn!).
I am very happy to try this new GUI out.

I look forward to keeping contact with you as I move forward with my experiments.

Best Regards,
Daniel Jakab,
